# Pandas Labs — Math Concepts in Code

**Format:** Guided walkthrough — each section has a **worked example** (run it, read it, understand it) followed by a **practice problem** for you to solve in the empty cell.

**Companion reading:** `PANDAS_MATH_CONCEPTS.md` in this folder.

**Prerequisite:** the NumPy module — Pandas builds directly on vectors/matrices, so make sure `shape`, `mean`/`std`, and basic array thinking feel comfortable first.

**Audience:** Absolute beginners.

In [1]:
import pandas as pd
import numpy as np
print("Pandas version:", pd.__version__)

Pandas version: 3.0.5


---
## Section 1 — Series & DataFrame ↔ Vector & Matrix

**Math idea:** a `Series` is a labeled vector. A `DataFrame` is a labeled matrix. Underneath, `df.values` is a plain NumPy array — everything from the NumPy module still applies.

In [2]:
# WORKED EXAMPLE
scores = pd.Series([85, 70, 90, 60], index=["Asha", "Ravi", "Meera", "Kabir"])
print(scores)

df = pd.DataFrame({
    "math":    [85, 70, 90, 60],
    "science": [90, 65, 88, 72],
    "english": [78, 80, 95, 68],
}, index=["Asha", "Ravi", "Meera", "Kabir"])
print(df)

print("underlying NumPy array:\n", df.values)
print("shape:", df.values.shape)

Asha     85
Ravi     70
Meera    90
Kabir    60
dtype: int64
       math  science  english
Asha     85       90       78
Ravi     70       65       80
Meera    90       88       95
Kabir    60       72       68
underlying NumPy array:
 [[85 90 78]
 [70 65 80]
 [90 88 95]
 [60 72 68]]
shape: (4, 3)


### Try it yourself
1. Create a `Series` called `city_pop` with 4 city names as the index and population numbers as values.
2. Create a `DataFrame` called `weather` with columns `temp_c` and `humidity` for 5 days (make up an index of day names).
3. Print `weather.values` and its `.shape` — confirm it's a plain NumPy 2-D array.

In [3]:
# YOUR CODE HERE


---
## Section 2 — Filtering ↔ Set Theory

**Math idea:** `{x ∈ S | P(x)}` — a boolean mask is the indicator function of a predicate `P`. `&` is set intersection (AND), `|` is set union (OR).

In [4]:
# WORKED EXAMPLE
mask = df["math"] > 75
print(mask)             # the indicator function itself: True/False per row

high_math = df[mask]
print(high_math)

strong_students = df[(df["math"] > 75) & (df["science"] > 75)]
print(strong_students)

Asha      True
Ravi     False
Meera     True
Kabir    False
Name: math, dtype: bool
       math  science  english
Asha     85       90       78
Meera    90       88       95
       math  science  english
Asha     85       90       78
Meera    90       88       95


### Try it yourself
Using the `df` from Section 1:
1. Filter for students who scored above 80 in `english`.
2. Filter for students who scored above 70 in `math` OR above 85 in `science` (use `|`).
3. Print just the `mask` (boolean Series) for condition 2 before applying it — describe in a comment what each `True`/`False` means.

In [5]:
# YOUR CODE HERE


---
## Section 3 — GroupBy ↔ Set Partitions + Aggregation

**Math idea:** `groupby` partitions rows into non-overlapping subsets by key, then applies a `Σ`-style aggregation to each subset independently.

In [6]:
# WORKED EXAMPLE
sales = pd.DataFrame({
    "region": ["North", "North", "South", "South", "East"],
    "amount": [100, 150, 200, 50, 300],
})

grouped_sum = sales.groupby("region")["amount"].sum()
print(grouped_sum)

summary = sales.groupby("region")["amount"].agg(["sum", "mean", "count"])
print(summary)

region
East     300
North    250
South    250
Name: amount, dtype: int64
        sum   mean  count
region                   
East    300  300.0      1
North   250  125.0      2
South   250  125.0      2


### Try it yourself
Given:
```python
orders = pd.DataFrame({
    "customer": ["A", "A", "B", "B", "C"],
    "item_price": [10, 25, 15, 40, 5],
})
```
1. Group by `customer` and compute the total spend per customer.
2. Group by `customer` and compute sum, mean, and count in one call.
3. In a comment, write out which rows form the partition for customer `"A"`, and confirm the sum manually.

In [7]:
# YOUR CODE HERE
orders = pd.DataFrame({
    "customer": ["A", "A", "B", "B", "C"],
    "item_price": [10, 25, 15, 40, 5],
})


---
## Section 4 — Merge / Join ↔ Relational Algebra

**Math idea:** `inner` join = intersection of keys, `outer` join = union of keys, `left`/`right` keep all of one side.

In [8]:
# WORKED EXAMPLE
students = pd.DataFrame({
    "student_id": [1, 2, 3],
    "name": ["Asha", "Ravi", "Meera"],
})
grades = pd.DataFrame({
    "student_id": [1, 2, 4],
    "grade": ["A", "B", "A"],
})

print("inner (intersection):\n", pd.merge(students, grades, on="student_id", how="inner"))
print("left:\n", pd.merge(students, grades, on="student_id", how="left"))
print("outer (union):\n", pd.merge(students, grades, on="student_id", how="outer"))

inner (intersection):
    student_id  name grade
0           1  Asha     A
1           2  Ravi     B
left:
    student_id   name grade
0           1   Asha     A
1           2   Ravi     B
2           3  Meera   NaN
outer (union):
    student_id   name grade
0           1   Asha     A
1           2   Ravi     B
2           3  Meera   NaN
3           4    NaN     A


### Try it yourself
```python
products = pd.DataFrame({"product_id": [1,2,3], "name": ["Pen","Book","Bag"]})
prices   = pd.DataFrame({"product_id": [2,3,4], "price": [20,150,300]})
```
1. Perform an inner join on `product_id`. Which products appear? Why (in terms of set intersection)?
2. Perform an outer join. Which cells are `NaN`, and why?
3. Perform a right join. How is it different from the outer join here?

In [9]:
# YOUR CODE HERE
products = pd.DataFrame({"product_id": [1,2,3], "name": ["Pen","Book","Bag"]})
prices   = pd.DataFrame({"product_id": [2,3,4], "price": [20,150,300]})


---
## Section 5 — Descriptive Stats & Covariance/Correlation Matrix

**Math idea:** column-wise mean/std are the same formulas from the NumPy module. The **covariance matrix** shows how every pair of columns varies together — and its eigenvectors (via `np.linalg.eig`) are exactly what PCA uses.

In [10]:
# WORKED EXAMPLE
print(df.mean())
print(df.std())
print(df.describe())

cov_matrix = df.cov()
corr_matrix = df.corr()
print("covariance matrix:\n", cov_matrix)
print("correlation matrix:\n", corr_matrix)

math       76.25
science    78.75
english    80.25
dtype: float64
math       13.768926
science    12.203142
english    11.146748
dtype: float64
            math    science    english
count   4.000000   4.000000   4.000000
mean   76.250000  78.750000  80.250000
std    13.768926  12.203142  11.146748
min    60.000000  65.000000  68.000000
25%    67.500000  70.250000  75.500000
50%    77.500000  80.000000  79.000000
75%    86.250000  88.500000  83.750000
max    90.000000  90.000000  95.000000
covariance matrix:
                math     science     english
math     189.583333  140.416667  127.916667
science  140.416667  148.916667   65.750000
english  127.916667   65.750000  124.250000
correlation matrix:
              math   science   english
math     1.000000  0.835693  0.833449
science  0.835693  1.000000  0.483366
english  0.833449  0.483366  1.000000


### Try it yourself
Using the `df` (math/science/english scores) from Section 1:
1. Print `df.describe()` and identify the column with the highest spread (std).
2. Compute `df.corr()`. Which two subjects correlate most strongly?
3. Feed the covariance matrix into `np.linalg.eig(df.cov())` (from the NumPy module) and print the eigenvalues — this is the first real step of PCA.

In [11]:
# YOUR CODE HERE


---
## Section 6 — Pivot Tables ↔ Cross-Tabulation

**Math idea:** turning long-format data into a matrix where rows/columns are two categorical variables — a reshape, like NumPy's `.reshape()` but keyed by labels instead of position.

In [12]:
# WORKED EXAMPLE
records = pd.DataFrame({
    "student": ["Asha", "Asha", "Ravi", "Ravi"],
    "subject": ["math", "science", "math", "science"],
    "score":   [85, 90, 70, 65],
})

pivoted = records.pivot(index="student", columns="subject", values="score")
print(pivoted)

subject  math  science
student               
Asha       85       90
Ravi       70       65


### Try it yourself
```python
logs = pd.DataFrame({
    "day": ["Mon","Mon","Tue","Tue","Wed","Wed"],
    "machine": ["A","B","A","B","A","B"],
    "units_produced": [100, 80, 110, 75, 90, 95],
})
```
1. Pivot this into a `day x machine` matrix of `units_produced`.
2. Use `pivot_table` with `aggfunc="mean"` instead, and explain in a comment when you'd need `pivot_table` over plain `pivot` (hint: duplicate index/column combos).

In [13]:
# YOUR CODE HERE
logs = pd.DataFrame({
    "day": ["Mon","Mon","Tue","Tue","Wed","Wed"],
    "machine": ["A","B","A","B","A","B"],
    "units_produced": [100, 80, 110, 75, 90, 95],
})


---
## Section 7 — Missing Data ↔ Partial Functions & Three-Valued Logic

**Math idea:** a column is a function from index to value. Missing data makes it a **partial** function — defined on part of the domain, undefined elsewhere. `isnull()` is the domain-membership predicate (same indicator-function idea as Section 2); `dropna()` restricts to where the function is defined; `fillna()` extends it back to a total function.

In [ ]:
# WORKED EXAMPLE
df_missing = df.copy()
df_missing.loc["Ravi", "math"] = np.nan
df_missing.loc["Meera", "science"] = np.nan
print(df_missing)

print(np.nan == np.nan)        # False -- "unknown = unknown" is still unknown
print(df_missing.isnull())     # indicator function, same idea as Section 2's boolean mask
print(df_missing.isnull().sum())

### Try it yourself
Using `df_missing` above:
1. Restrict to only the fully-defined rows with `dropna()`. How many rows remain, and why?
2. Restrict to rows where `math` specifically is defined, using `dropna(subset=...)`.
3. Make a copy called `df_filled`, and extend `math` and `science` to total functions by filling each with its own column mean (computed from `df_missing`, before filling).
4. Compare `df_missing["math"].sum()` (default) with `df_missing["math"].sum(skipna=False)`. In a comment, explain the difference in terms of "sum over a subset" vs. "undefined poisons the result."

In [ ]:
# YOUR CODE HERE



---
## Mini-Project — Put it all together

**Scenario:** You run a small online store. You have two tables:

```python
orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer": ["A", "B", "A", "C", "B", "A"],
    "category": ["Electronics", "Books", "Books", "Electronics", "Electronics", "Toys"],
    "amount": [500, 20, 15, 700, 250, 40],
})
customers = pd.DataFrame({
    "customer": ["A", "B", "C", "D"],
    "city": ["Hyderabad", "Chennai", "Delhi", "Pune"],
})
```

Tasks:
1. Merge `orders` with `customers` (left join, keep all orders) to attach each order's city.
2. Group the merged table by `customer` and compute total `amount` spent per customer (a partition + `Σ`).
3. Group by `category` and compute mean order `amount` per category.
4. Pivot the merged table into a `customer x category` matrix of total `amount` (use `pivot_table` with `aggfunc="sum"` and `fill_value=0`, since not every customer bought every category).
5. On that pivoted matrix, compute `.corr()` between categories — do customers who spend more on Electronics also spend more on Toys? Then run `np.linalg.eig()` on the covariance matrix of the pivoted table, connecting straight back to the NumPy module.

In [14]:
# YOUR CODE HERE
orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer": ["A", "B", "A", "C", "B", "A"],
    "category": ["Electronics", "Books", "Books", "Electronics", "Electronics", "Toys"],
    "amount": [500, 20, 15, 700, 250, 40],
})
customers = pd.DataFrame({
    "customer": ["A", "B", "C", "D"],
    "city": ["Hyderabad", "Chennai", "Delhi", "Pune"],
})


---
## Wrap-up

You've now connected Pandas code to: labeled vectors/matrices, set-theoretic filtering, partition + aggregation (groupby), relational algebra (merge/join), covariance/correlation matrices, cross-tabulation (pivot), and missing data (partial functions).

**Next module:** Matplotlib — visualizing the vectors, distributions, and functions we've been computing.