# NumPy Labs — Math Concepts in Code

**Format:** Guided walkthrough — each section has a **worked example** (run it, read it, understand it) followed by a **practice problem** for you to solve in the empty cell.

**Companion reading:** `NUMPY_MATH_CONCEPTS.md` in this folder — read the matching section there if a worked example doesn't make sense.

**Audience:** Absolute beginners. No prior linear algebra assumed — every formula is explained in plain language before the code.

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.5.1


---
## Section 1 — Scalars, Vectors, Matrices, Tensors

**Math idea:** we classify numbers by how many axes (directions) they need — a scalar (0 axes), a vector (1 axis), a matrix (2 axes), a tensor (N axes).

In [2]:
# WORKED EXAMPLE
scalar = np.array(7)
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])

for name, arr in [("scalar", scalar), ("vector", vector), ("matrix", matrix)]:
    print(f"{name}: shape={arr.shape}, ndim={arr.ndim}")

scalar: shape=(), ndim=0
vector: shape=(3,), ndim=1
matrix: shape=(2, 2), ndim=2


### Try it yourself
1. Create a 3x3 matrix called `identity_like` using `np.array` (any numbers, must be 3 rows x 3 columns).
2. Print its `.shape` and `.ndim`.
3. Create a tensor of shape `(2, 2, 2)` called `cube` and print its shape.

In [3]:
# YOUR CODE HERE


---
## Section 2 — Vector Operations

**Math idea:** the **dot product** `v · w = Σ vᵢwᵢ` tells you how much two vectors point in the same direction. The **norm** `‖v‖ = √(Σvᵢ²)` tells you a vector's length.

In [4]:
# WORKED EXAMPLE
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print("v + w      =", v + w)
print("2 * v      =", 2 * v)
print("v . w      =", np.dot(v, w))
print("||v||      =", np.linalg.norm(v))
print("distance(v,w) =", np.linalg.norm(v - w))

v + w      = [5 7 9]
2 * v      = [2 4 6]
v . w      = 32
||v||      = 3.7416573867739413
distance(v,w) = 5.196152422706632


### Try it yourself
Given `a = [3, 4]` and `b = [0, 0]`:
1. Compute the dot product of `a` and `b`.
2. Compute `‖a‖` (the norm of `a`). What real-world quantity does this number represent if `a` is a point on a 2D plane? (Answer in a comment.)
3. Compute the distance between `a` and `b` using `np.linalg.norm`.

In [5]:
# YOUR CODE HERE
a = np.array([3, 4])
b = np.array([0, 0])


---
## Section 3 — Matrix Operations

**Math idea:** `*` multiplies element-by-element. `@` performs true **matrix multiplication**: `(AB)ᵢⱼ = Σₖ Aᵢₖ Bₖⱼ`. These are NOT the same thing — this is the #1 beginner mistake in NumPy.

In [6]:
# WORKED EXAMPLE
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A * B (element-wise):\n", A * B)
print("A @ B (matrix multiplication):\n", A @ B)
print("A transpose:\n", A.T)
print("determinant of A:", np.linalg.det(A))
print("inverse of A:\n", np.linalg.inv(A))

# Solve Ax = b
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print("solution x of A x = b:", x)

A * B (element-wise):
 [[ 5 12]
 [21 32]]
A @ B (matrix multiplication):
 [[19 22]
 [43 50]]
A transpose:
 [[1 3]
 [2 4]]
determinant of A: -2.0000000000000004
inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
solution x of A x = b: [-10.    9.5]


### Try it yourself
1. Create two 2x2 matrices `C` and `D` of your choice.
2. Print both `C * D` and `C @ D` — confirm they give different results.
3. Check that `C @ np.linalg.inv(C)` is (approximately) the identity matrix.
4. Solve the system: `2x + y = 5`, `x + 3y = 10` using `np.linalg.solve`.

In [7]:
# YOUR CODE HERE


---
## Section 4 — Broadcasting

**Math idea:** broadcasting lets NumPy combine arrays of different shapes by conceptually "stretching" the smaller one. This is how we mean-center data: subtract a single row (the column means) from every row of a matrix.

In [8]:
# WORKED EXAMPLE
data = np.array([
    [10, 200],
    [12, 220],
    [ 9, 180],
    [14, 240],
])

col_means = data.mean(axis=0)
print("column means:", col_means)

centered = data - col_means   # broadcasting: (4,2) - (2,) -> (4,2)
print("centered data:\n", centered)
print("new column means (should be ~0):", centered.mean(axis=0))

column means: [ 11.25 210.  ]
centered data:
 [[ -1.25 -10.  ]
 [  0.75  10.  ]
 [ -2.25 -30.  ]
 [  2.75  30.  ]]
new column means (should be ~0): [0. 0.]


### Try it yourself
1. Using the `data` matrix above, compute the column standard deviations with `data.std(axis=0)`.
2. Standardize `data` (subtract column mean, divide by column std) in one line — call the result `standardized`.
3. Verify `standardized.mean(axis=0)` is ~0 and `standardized.std(axis=0)` is ~1.

In [9]:
# YOUR CODE HERE


---
## Section 5 — Basic Statistics

**Math idea:** mean `μ = (1/n)Σxᵢ`, variance `σ² = (1/n)Σ(xᵢ-μ)²`, standard deviation `σ = √σ²`. These describe the center and spread of a dataset.

In [10]:
# WORKED EXAMPLE
scores = np.array([55, 60, 65, 70, 70, 75, 80, 95])

print("mean:", scores.mean())
print("variance:", scores.var())
print("std:", scores.std())

z_scores = (scores - scores.mean()) / scores.std()
print("z-scores:", z_scores)

mean: 71.25
variance: 135.9375
std: 11.659223816361019
z-scores: [-1.3937463  -0.96490128 -0.53605627 -0.10721125 -0.10721125  0.32163376
  0.75047877  2.03701382]


### Try it yourself
Given `temps = np.array([30, 32, 29, 35, 40, 28, 31])` (daily temperatures in °C):
1. Compute mean, variance, std.
2. Compute the z-score of the hottest day. Is it an outlier (|z| > 2)?
3. Standardize the whole array.

In [11]:
# YOUR CODE HERE
temps = np.array([30, 32, 29, 35, 40, 28, 31])


---
## Section 6 — Eigenvalues, Eigenvectors & SVD (preview)

**Math idea:** `A v = λ v` — an eigenvector `v` of matrix `A` keeps its direction under the transformation `A`, only getting scaled by the eigenvalue `λ`. We'll use this heavily when we cover PCA in the scikit-learn module; for now, just get comfortable calling the functions and reading the output.

In [12]:
# WORKED EXAMPLE
A = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("eigenvalues:", eigenvalues)
print("eigenvectors:\n", eigenvectors)

# Verify: A @ v should equal lambda * v for each eigenvector
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    print(f"A @ v = {A @ v},  lambda * v = {lam * v}")

eigenvalues: [2.+0.j 3.+0.j]
eigenvectors:
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
A @ v = [2.+0.j 0.+0.j],  lambda * v = [2.+0.j 0.+0.j]
A @ v = [0.+0.j 3.+0.j],  lambda * v = [0.+0.j 3.+0.j]


### Try it yourself
1. Find the eigenvalues and eigenvectors of `M = np.array([[4, 1], [2, 3]])`.
2. Verify `M @ v ≈ lambda * v` for each eigenvector (like the worked example).
3. Run `U, S, Vt = np.linalg.svd(M)` and print `S` (the singular values).

In [13]:
# YOUR CODE HERE


---
## Mini-Project — Put it all together

**Scenario:** You have exam scores for 5 students across 3 subjects (Math, Science, English). Use only NumPy to analyze it.

```python
scores = np.array([
    [85, 90, 78],
    [70, 65, 80],
    [90, 88, 95],
    [60, 72, 68],
    [75, 80, 85],
])  # rows = students, columns = [Math, Science, English]
```

Tasks:
1. Compute each subject's average score (column means).
2. Compute each student's average score (row means).
3. Standardize the whole matrix (subtract column mean, divide by column std) — this is the same first step used before running PCA.
4. Compute the **covariance matrix** of the standardized data with `np.cov(standardized, rowvar=False)` — this tells you how subjects move together (e.g., do students who score high in Math also score high in Science?).
5. Find the eigenvalues of the covariance matrix with `np.linalg.eig`. The largest eigenvalue corresponds to the direction of most variation in the data — this *is* the first step of PCA, which we'll build fully in the scikit-learn module.

In [14]:
# YOUR CODE HERE
scores = np.array([
    [85, 90, 78],
    [70, 65, 80],
    [90, 88, 95],
    [60, 72, 68],
    [75, 80, 85],
])


---
## Wrap-up

You've now connected NumPy code to: vectors, matrices, dot products, norms, matrix multiplication, inverses, determinants, solving linear systems, broadcasting, mean/variance/std, and eigenvalues/SVD.

**Next module:** Pandas — we'll extend the matrix idea (rows x columns) into labeled, real-world tabular data, and connect `groupby`/`merge` to relational algebra and aggregation math.